### ISSUE TITLE
Missing export of INTL_RELATIVE_TIME_PIPE_DEFAULT_OPTIONS in "angular-ecmascript-intl"

### ISSUE THREAD

**Issue by addielmoldes** [json-derulo/angular-ecmascript-intl#307]
When trying to inject  INTL_RELATIVE_TIME_PIPE_DEFAULT_OPTIONS token in App Module providers.

Output: 
Error: Module not found: Error: Package path ./lib/relative-time/relative-time-pipe-default-options is not exported from package /home/addiel/Documents/Proyectos/plaza_frontend/node_modules/angular-ecmascript-intl (see exports field in /home/addiel/Documents/Proyectos/plaza_frontend/node_modules/angular-ecmascript-intl/package.json)

![Screenshot from 2024-04-09 15-15-14](https://github.com/json-derulo/angular-ecmascript-intl/assets/105292535/846b95a0-abdc-4582-9dca-9f2859b14113)

export should be below export * from './lib/relative-time/relative-time.pipe';

My Angular's version is 17.3.3 and Angular Intl latest 3.0.0

**Comment by json-derulo** [comment]
Hi, thanks for opening the issue. It looks like this export is really missing. Could you explain why you closed the issue?

**Comment by addielmoldes** [comment]
I thought the pipe wasn't working because the relative time in component's template was always 0, but then I realized it was my mistake because I had set the date  in the mock up object I use to test to always new Date().

It actually was a confusion to close the issue because I thought it was my mistake, but the export of the relative time options token is really missing, so it crashes when you try to provide it.

**Comment by json-derulo** [comment]
Thanks for the explanation. I will re-open this issue for tracking the problem with the injection token.

**Comment by json-derulo** [comment]
Fixed with v3.0.1
